drop table BPApplications;
drop table BPEmployers;
drop table BPStages;
drop table BPJobs;

create table BPJobs(
JobId number generated by default on null as identity primary key,
Tittle VARCHAR2(100),
JobDescription varchar2(500),
JobType varchar2(100),
Openings NUMBER
);


create table BPApplications(
  BPApplicationId number generated by default on null as identity primary key,
  JobId number,
  FullName varchar2(100),
  Email varchar2(100),
  Address varchar2(200),
  Birthday varchar2(100),
  Education varchar2(100),
  JobHistory varchar2(500),
  references varchar2(300),
  druguse varchar2(100),
  veteran varchar2(100),
  citizenship varchar2(100),
  status varchar2(100),
  foreign key (JobId) references BPJobs(JObId)
);

create table BPEmployers(
BPEmployerID number generated by default on null as identity primary key,
name varchar2(100),
role VARCHAR2(100),
email varchar2(100),
hashpassword varchar2(100)
);


create table BPstages(
BPstageId number generated by default on null as identity primary key,
BPApplicationId number,
BPemployerId number,
stagename varchar2(100),
stagecomment varchar2(500),
stageresult varchar2(100),
FOREIGN key (BPApplicationId) references BPApplications(BPApplicationId),
FOREIGN key (BPemployerId) references BPEmployers(BPemployerId)
);
