drop table BPApplications;
drop table BPEmployers;
drop table BPStages;
drop table BPJobs;

create table BPJobs(
JobId number generated by default on null as identity primary key,
Tittle VARCHAR2(100),
JobDescription varchar2(500),
JobType varchar2(100),
Openings NUMBER
);


create table BPApplications(
  BPApplicationId number generated by default on null as identity primary key,
  JobId number,
  FullName varchar2(100),
  Email varchar2(100),
  Address varchar2(200),
  Birthday varchar2(100),
  Education varchar2(100),
  JobHistory varchar2(500),
  references varchar2(300),
  druguse varchar2(100),
  veteran varchar2(100),
  citizenship varchar2(100),
  status varchar2(100),
  foreign key (JobId) references BPJobs(JObId)
);

create table BPEmployers(
BPEmployerID number generated by default on null as identity primary key,
name varchar2(100),
role VARCHAR2(100),
email varchar2(100),
hashpassword varchar2(100)
);


create table BPstages(
BPstageId number generated by default on null as identity primary key,
BPApplicationId number,
BPemployerId number,
stagename varchar2(100),
stagecomment varchar2(500),
stageresult varchar2(100),
FOREIGN key (BPApplicationId) references BPApplications(BPApplicationId),
FOREIGN key (BPemployerId) references BPEmployers(BPemployerId)
);

ALTER TABLE Bpapplications
ADD summary varchar2(200);

ALTER TABLE Bpapplications
ADD Objective varchar2(200);

ALTER TABLE Bpapplications
ADD skills varchar2(300);

ALTER TABLE Bpstages
ADD score number;

create table BpQuestions(
questionId number generated by default on null as identity primary key,
tittle varchar2(100),
questiontype varchar2(100),
question varchar2(300)
);

create table BpUsers(
UserId number generated by default on null as identity primary key,
email varchar2(100),
passwordhash varchar2(100),
summary varchar2(300),
objective varchar2(200),
address varchar2(300),
skills varchar2(300),
education varchar2(400),
awards varchar2(500)
);