--------------------------------------------------------
--  File created - Wednesday-October-26-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BPAPPLICATIONS
--------------------------------------------------------

  CREATE TABLE "ORA1"."BPAPPLICATIONS" 
   (	"BPAPPLICATIONID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"JOBID" NUMBER, 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"BIRTHDAY" VARCHAR2(100 BYTE), 
	"EDUCATION" VARCHAR2(100 BYTE), 
	"JOBHISTORY" VARCHAR2(500 BYTE), 
	"REFERENCES" VARCHAR2(300 BYTE), 
	"DRUGUSE" VARCHAR2(100 BYTE), 
	"VETERAN" VARCHAR2(100 BYTE), 
	"CITIZENSHIP" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"SUMMARY" VARCHAR2(200 BYTE), 
	"OBJECTIVE" VARCHAR2(200 BYTE), 
	"SKILLS" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BPEMPLOYERS
--------------------------------------------------------

  CREATE TABLE "ORA1"."BPEMPLOYERS" 
   (	"BPEMPLOYERID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"NAME" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"HASHPASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BPJOBS
--------------------------------------------------------

  CREATE TABLE "ORA1"."BPJOBS" 
   (	"JOBID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"TITTLE" VARCHAR2(100 BYTE), 
	"JOBDESCRIPTION" VARCHAR2(500 BYTE), 
	"JOBTYPE" VARCHAR2(100 BYTE), 
	"OPENINGS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BPQUESTIONS
--------------------------------------------------------

  CREATE TABLE "ORA1"."BPQUESTIONS" 
   (	"QUESTIONID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"TITTLE" VARCHAR2(100 BYTE), 
	"QUESTIONTYPE" VARCHAR2(100 BYTE), 
	"QUESTION" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BPSTAGES
--------------------------------------------------------

  CREATE TABLE "ORA1"."BPSTAGES" 
   (	"BPSTAGEID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"BPAPPLICATIONID" NUMBER, 
	"BPEMPLOYERID" NUMBER, 
	"STAGENAME" VARCHAR2(100 BYTE), 
	"STAGECOMMENT" VARCHAR2(500 BYTE), 
	"STAGERESULT" VARCHAR2(100 BYTE), 
	"SCORE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORA1.BPAPPLICATIONS
SET DEFINE OFF;
Insert into ORA1.BPAPPLICATIONS (BPAPPLICATIONID,JOBID,FULLNAME,EMAIL,BIRTHDAY,EDUCATION,JOBHISTORY,REFERENCES,DRUGUSE,VETERAN,CITIZENSHIP,STATUS,ADDRESS,SUMMARY,OBJECTIVE,SKILLS) values (352,4,'Neha Jamwal','neha@j.com','18th March','Engineer','Technical Analyst, IPS','References.','no','no','India','hired','Potomac , MD','Business and Technology Applicant','To conquer the world','Java');
Insert into ORA1.BPAPPLICATIONS (BPAPPLICATIONID,JOBID,FULLNAME,EMAIL,BIRTHDAY,EDUCATION,JOBHISTORY,REFERENCES,DRUGUSE,VETERAN,CITIZENSHIP,STATUS,ADDRESS,SUMMARY,OBJECTIVE,SKILLS) values (343,4,'Anju Kumar ','anju@test.com','1st Oct 1992','Engineer','Technical Analyst','N/A','no','no','Indian','declined','Halpine Rd','brief consulting  experience ','test objective ','java, vb , C++');
REM INSERTING into ORA1.BPEMPLOYERS
SET DEFINE OFF;
Insert into ORA1.BPEMPLOYERS (BPEMPLOYERID,NAME,ROLE,EMAIL,HASHPASSWORD) values (256,'Dave','complianceofficer','c@d.com','6a3eea915214c77d5f00abea445c31443e176e385b16564eefc69f25a61ac404');
Insert into ORA1.BPEMPLOYERS (BPEMPLOYERID,NAME,ROLE,EMAIL,HASHPASSWORD) values (257,'Sam','hrassistant','ha@d.com','fc26479460fea1f4285f01eea5d1420ca8f8d258a786e512b1336b39d2aea049');
Insert into ORA1.BPEMPLOYERS (BPEMPLOYERID,NAME,ROLE,EMAIL,HASHPASSWORD) values (258,'Tom','hrspecialist','hs@d.com','79d0c35c549d69587c5e5e0bc5d3775ace6955a8c12874d7d7d45d0ccbfe8fd8');
Insert into ORA1.BPEMPLOYERS (BPEMPLOYERID,NAME,ROLE,EMAIL,HASHPASSWORD) values (259,'Jack','healthcarespecialist','hcs@d.com','48c72dda05f9b1684011816b9d50c48a6ffdb46e1b778ffdeeb9687b5202111e');
Insert into ORA1.BPEMPLOYERS (BPEMPLOYERID,NAME,ROLE,EMAIL,HASHPASSWORD) values (260,'John','hrmanager','hm@d.com','3594a887957e42ee8cdbd7d49c118f0caab7df25f1b8ee3bdb5887d26927abb4');
Insert into ORA1.BPEMPLOYERS (BPEMPLOYERID,NAME,ROLE,EMAIL,HASHPASSWORD) values (261,'oliver','hiringmanager','him@d.com','edb21e1de06f7f9fc721a90bc7623964bd4747aa2194339a5cb4e101d994da1f');
Insert into ORA1.BPEMPLOYERS (BPEMPLOYERID,NAME,ROLE,EMAIL,HASHPASSWORD) values (262,'caramel','interviewleader','il@d.com','28aa1e1bc5b4fb9e789fc8673ddbb1d27f576a677bdfecedec4bfd547c56171f');
REM INSERTING into ORA1.BPJOBS
SET DEFINE OFF;
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (1,'Technical Analyst ','A TA is esponsible for bridging the gap between business process and technical requirements ','Technical',2);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (2,'Technical Lead','A TL leads the team systems engineers and TAs','Technical',1);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (3,'Project Manager','A project manager is responsible for planning and managing all stages of a given project','Management',4);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (4,'Consultant','Shoulders the responsiblity of building solutions and strategies for various issues and cases','Consulting',6);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (5,'Systems Engineer','Developing and testing different software and solutions for the client\','Technical',3);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (6,'Janitor','Cleaning and maintaining the office ','Maintenence',1);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (7,'CEO','Badass Boss','Management',1);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (240,'Associate Consultant','Assists the consulting in creating effiecient strategies. leads the team of analysts.','Technical',4);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (241,'Manager','Leads the team , build proposals and brings in sales.','Technical',4);
Insert into ORA1.BPJOBS (JOBID,TITTLE,JOBDESCRIPTION,JOBTYPE,OPENINGS) values (242,'Cleaning and Maintence staff','Responsible for the overall maintence of the workplace','Maintenence',4);
REM INSERTING into ORA1.BPQUESTIONS
SET DEFINE OFF;
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (111,'Technical Analyst','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (112,'Technical Analyst','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (113,'Technical Analyst','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (114,'Technical Analyst','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (115,'Technical Analyst','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (116,'Technical Analyst','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (117,'Technical Analyst','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (118,'Technical Analyst','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (119,'Technical Analyst','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (100,'Technical Analyst','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (101,'Technical Analyst','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (102,'Technical Analyst','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (103,'Technical Analyst','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (104,'Technical Analyst','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (105,'Technical Analyst','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (106,'Technical Analyst','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (107,'Technical Analyst','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (108,'Technical Analyst','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (109,'Technical Analyst','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (110,'Technical Analyst','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (120,'Technical Analyst','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (121,'Technical Analyst','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (122,'Technical Analyst','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (123,'Technical Analyst','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (124,'Technical Analyst','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (125,'Technical Analyst','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (126,'Technical Analyst','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (127,'Technical Analyst','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (128,'Technical Analyst','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (129,'Technical Analyst','groupinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (130,'Technical Lead','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (131,'Technical Lead','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (132,'Technical Lead','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (133,'Technical Lead','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (134,'Technical Lead','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (135,'Technical Lead','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (136,'Technical Lead','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (137,'Technical Lead','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (138,'Technical Lead','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (139,'Technical Lead','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (140,'Technical Lead','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (141,'Technical Lead','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (142,'Technical Lead','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (143,'Technical Lead','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (144,'Technical Lead','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (145,'Technical Lead','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (146,'Technical Lead','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (147,'Technical Lead','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (148,'Technical Lead','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (149,'Technical Lead','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (150,'Technical Lead','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (151,'Technical Lead','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (152,'Technical Lead','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (153,'Technical Lead','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (154,'Technical Lead','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (155,'Technical Lead','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (156,'Technical Lead','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (157,'Technical Lead','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (158,'Technical Lead','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (159,'Technical Lead','groupinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (160,'Consultant','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (162,'Consultant','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (163,'Consultant','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (164,'Consultant','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (165,'Consultant','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (166,'Consultant','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (167,'Consultant','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (168,'Consultant','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (169,'Consultant','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (170,'Consultant','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (171,'Consultant','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (172,'Consultant','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (173,'Consultant','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (174,'Consultant','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (175,'Consultant','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (176,'Consultant','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (177,'Consultant','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (178,'Consultant','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (179,'Consultant','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (180,'Consultant','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (181,'Consultant','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (182,'Consultant','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (183,'Consultant','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (184,'Consultant','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (185,'Consultant','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (186,'Consultant','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (187,'Consultant','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (188,'Consultant','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (189,'Consultant','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (190,'Consultant','groupinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (191,'Systems Engineer','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (193,'Systems Engineer','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (194,'Systems Engineer','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (195,'Systems Engineer','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (196,'Systems Engineer','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (197,'Systems Engineer','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (198,'Systems Engineer','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (199,'Systems Engineer','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (200,'Systems Engineer','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (201,'Systems Engineer','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (202,'Systems Engineer','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (203,'Systems Engineer','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (204,'Systems Engineer','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (205,'Systems Engineer','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (206,'Systems Engineer','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (207,'Systems Engineer','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (208,'Systems Engineer','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (209,'Systems Engineer','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (210,'Systems Engineer','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (211,'Systems Engineer','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (212,'Systems Engineer','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (213,'Systems Engineer','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (214,'Systems Engineer','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (215,'Systems Engineer','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (216,'Systems Engineer','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (217,'Systems Engineer','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (218,'Systems Engineer','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (219,'Systems Engineer','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (220,'Systems Engineer','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (221,'Systems Engineer','groupinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (222,'Associate Consultant','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (223,'Associate Consultant','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (224,'Associate Consultant','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (225,'Associate Consultant','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (226,'Associate Consultant','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (227,'Associate Consultant','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (228,'Associate Consultant','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (229,'Associate Consultant','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (230,'Associate Consultant','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (231,'Associate Consultant','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (232,'Associate Consultant','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (233,'Associate Consultant','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (234,'Associate Consultant','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (235,'Associate Consultant','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (236,'Associate Consultant','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (237,'Associate Consultant','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (238,'Associate Consultant','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (239,'Associate Consultant','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (240,'Associate Consultant','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (241,'Associate Consultant','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (242,'Associate Consultant','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (243,'Associate Consultant','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (244,'Associate Consultant','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (245,'Associate Consultant','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (246,'Associate Consultant','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (247,'Associate Consultant','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (248,'Associate Consultant','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (249,'Associate Consultant','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (250,'Associate Consultant','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (251,'Associate Consultant','groupinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (252,'Project Manager','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (253,'Project Manager','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (254,'Project Manager','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (255,'Project Manager','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (256,'Project Manager','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (257,'Project Manager','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (258,'Project Manager','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (259,'Project Manager','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (260,'Project Manager','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (261,'Project Manager','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (262,'Project Manager','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (263,'Project Manager','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (264,'Project Manager','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (265,'Project Manager','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (266,'Project Manager','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (267,'Project Manager','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (268,'Project Manager','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (269,'Project Manager','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (270,'Project Manager','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (271,'Project Manager','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (272,'Project Manager','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (273,'Project Manager','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (274,'Project Manager','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (275,'Project Manager','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (276,'Project Manager','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (277,'Project Manager','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (278,'Project Manager','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (279,'Project Manager','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (280,'Project Manager','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (281,'Project Manager','groupinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (282,'Manager','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (283,'Manager','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (284,'Manager','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (285,'Manager','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (286,'Manager','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (287,'Manager','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (288,'Manager','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (289,'Manager','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (290,'Manager','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (291,'Manager','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (292,'Manager','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (293,'Manager','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (294,'Manager','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (295,'Manager','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (296,'Manager','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (297,'Manager','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (298,'Manager','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (299,'Manager','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (300,'Manager','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (301,'Manager','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (302,'Manager','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (303,'Manager','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (304,'Manager','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (305,'Manager','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (306,'Manager','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (307,'Manager','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (308,'Manager','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (309,'Manager','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (310,'Manager','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (311,'Manager','groupinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (313,'CEO','secondinterview','Describe a time you made a risky decisions. How did that work out?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (314,'CEO','secondinterview','What applicable experience do you have?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (315,'CEO','secondinterview','If you were hiring for this position, what qualities would you look for in a potential candidate?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (316,'CEO','secondinterview','Tell us some of your strengths.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (317,'CEO','secondinterview','Tell us some of your weaknesses.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (318,'CEO','secondinterview','Where do you see yourself in 5 years?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (319,'CEO','secondinterview','What can you contribute to this company and their products?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (320,'CEO','secondinterview','What is Your Sense of Our Corporate Environment?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (321,'CEO','secondinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (322,'CEO','hrinterview','Why are you interested in this position?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (323,'CEO','hrinterview','Why are you leaving your current job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (324,'CEO','hrinterview','What is the one thing that makes this company a right fit for you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (325,'CEO','hrinterview','What is your expected salary?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (326,'CEO','hrinterview','What do you know about us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (327,'CEO','hrinterview','Will you be happy to re-locate, if required?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (328,'CEO','hrinterview','Will you be able to travel 20%- 60%');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (329,'CEO','hrinterview','Why are you leaving your previous job?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (330,'CEO','hrinterview','Why should we hire you?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (331,'CEO','hrinterview','Do you have any questions for us?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (332,'CEO','secondinterview','Tell us about a time you were creative?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (333,'CEO','groupinterview','Find out three facts about the person sitting next to you, and share with the group');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (334,'CEO','groupinterview','If you could invite two famous people to your dinner party, who would you choose?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (335,'CEO','groupinterview','Sell this pen to the person sitting next to you.');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (336,'CEO','groupinterview','In a team of 3 , use the fewest possible bricks to build the highest free-standing structure');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (337,'CEO','groupinterview','What made your team work successfully');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (338,'CEO','groupinterview','What stopped your team from achieving the objective');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (339,'CEO','groupinterview','How did you deal with problems during the group activity');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (340,'CEO','groupinterview','If you could redo the activity, what would you change?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (341,'CEO','groupinterview','If you were the interviewer , other than you, who in the group would you hire and why?');
Insert into ORA1.BPQUESTIONS (QUESTIONID,TITTLE,QUESTIONTYPE,QUESTION) values (342,'CEO','groupinterview','Do you have any questions for us?');
REM INSERTING into ORA1.BPSTAGES
SET DEFINE OFF;
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (353,352,256,'nationality','Passed','passed',9);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (344,343,256,'nationality','Sponsorship required','passed',9);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (355,352,258,'degree','Degree verified','passed',8);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (356,352,259,'drugstandard','Standard is clear','passed',10);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (357,352,259,'drugpot','DoT is clear','passed',10);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (358,352,259,'drugalchol','Alcohol is clear','passed',10);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (359,352,257,'veteran','not a veteran - confirmed','passed',10);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (360,352,260,'hrinterview','Overall well done','passed',9);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (354,352,257,'history','history is checked','passed',5);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (361,352,261,'secondinterview','Good','passed',10);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (362,352,262,'groupinterview','must hire','passed',10);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (345,343,257,'history','Not a veteran - verified','passed',9);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (346,343,258,'degree','Degree - verified','passed',8);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (347,343,259,'drugstandard','No drug traces found in standard testing','passed',9);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (348,343,259,'drugpot','no drug traces found in drug - pot testing','passed',9);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (349,343,259,'drugalchol',null,'passed',8);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (350,343,257,'veteran','Not a veteran','passed',10);
Insert into ORA1.BPSTAGES (BPSTAGEID,BPAPPLICATIONID,BPEMPLOYERID,STAGENAME,STAGECOMMENT,STAGERESULT,SCORE) values (351,343,260,'hrinterview','Candidate was prepared - Overall 7/10','failed',7);
--------------------------------------------------------
--  DDL for Index SYS_C0011144
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0011144" ON "ORA1"."BPAPPLICATIONS" ("BPAPPLICATIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011147
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0011147" ON "ORA1"."BPEMPLOYERS" ("BPEMPLOYERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011142
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0011142" ON "ORA1"."BPJOBS" ("JOBID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011205
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0011205" ON "ORA1"."BPQUESTIONS" ("QUESTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011149
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0011149" ON "ORA1"."BPSTAGES" ("BPSTAGEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BPAPPLICATIONS
--------------------------------------------------------

  ALTER TABLE "ORA1"."BPAPPLICATIONS" ADD PRIMARY KEY ("BPAPPLICATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."BPAPPLICATIONS" MODIFY ("BPAPPLICATIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPEMPLOYERS
--------------------------------------------------------

  ALTER TABLE "ORA1"."BPEMPLOYERS" ADD PRIMARY KEY ("BPEMPLOYERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."BPEMPLOYERS" MODIFY ("BPEMPLOYERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPJOBS
--------------------------------------------------------

  ALTER TABLE "ORA1"."BPJOBS" ADD PRIMARY KEY ("JOBID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."BPJOBS" MODIFY ("JOBID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPQUESTIONS
--------------------------------------------------------

  ALTER TABLE "ORA1"."BPQUESTIONS" ADD PRIMARY KEY ("QUESTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."BPQUESTIONS" MODIFY ("QUESTIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BPSTAGES
--------------------------------------------------------

  ALTER TABLE "ORA1"."BPSTAGES" ADD PRIMARY KEY ("BPSTAGEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."BPSTAGES" MODIFY ("BPSTAGEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BPAPPLICATIONS
--------------------------------------------------------

  ALTER TABLE "ORA1"."BPAPPLICATIONS" ADD FOREIGN KEY ("JOBID")
	  REFERENCES "ORA1"."BPJOBS" ("JOBID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BPSTAGES
--------------------------------------------------------

  ALTER TABLE "ORA1"."BPSTAGES" ADD FOREIGN KEY ("BPAPPLICATIONID")
	  REFERENCES "ORA1"."BPAPPLICATIONS" ("BPAPPLICATIONID") ENABLE;
  ALTER TABLE "ORA1"."BPSTAGES" ADD FOREIGN KEY ("BPEMPLOYERID")
	  REFERENCES "ORA1"."BPEMPLOYERS" ("BPEMPLOYERID") ENABLE;
